# Generated by Django 3.2.5 on 2021-11-17 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20211117_0759'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectowner',
            options={'verbose_name': 'project_owner', 'verbose_name_plural': 'project_owners'},
        ),
    ]
