# Generated by Django 3.2.5 on 2021-11-17 08:55

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_alter_projectowner_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('goal', models.IntegerField(validators=[django.core.validators.MinValueValidator(1, 'goal should be greater than zero')])),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='project.category')),
                ('projectowner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='project.projectowner')),
            ],
            options={
                'verbose_name': 'project',
                'verbose_name_plural': 'projects',
                'ordering': ('title',),
            },
        ),
    ]
