# Generated by Django 3.2.5 on 2021-11-17 09:42

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectSupport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('price', models.IntegerField(validators=[django.core.validators.MinValueValidator(1, 'goal should be greater than zero')])),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projectsupports', to='project.project')),
            ],
            options={
                'verbose_name': 'projectsupport',
                'verbose_name_plural': 'projectsupports',
            },
        ),
    ]
