# Generated by Django 3.2.5 on 2021-11-17 10:39

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0006_projectsupport'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pleadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectName', models.CharField(max_length=50)),
                ('price', models.IntegerField(validators=[django.core.validators.MinValueValidator(1, 'goal should be greater than zero')])),
                ('issuedate', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid'), ('expired', 'Expired')], default='unpaid', max_length=50)),
                ('supportname', models.CharField(max_length=50)),
                ('supportprice', models.IntegerField(validators=[django.core.validators.MinValueValidator(1, 'goal should be greater than zero')])),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1, 'goal should be greater than zero')])),
                ('projectsupport', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pleadge', to='project.projectsupport')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
