# Generated by Django 3.2.5 on 2021-11-17 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_pleadge'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pleadge',
            options={'verbose_name': 'pleadge', 'verbose_name_plural': 'pleadges'},
        ),
    ]
