# Generated by Django 3.2.5 on 2021-11-17 14:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_alter_pleadge_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pleadge',
            name='price',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1, 'price must be greater than 0')]),
        ),
        migrations.AlterField(
            model_name='pleadge',
            name='quantity',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1, 'quantity must greater than 0')]),
        ),
        migrations.AlterField(
            model_name='pleadge',
            name='supportprice',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1, 'price must be greater than 0')]),
        ),
        migrations.AlterField(
            model_name='project',
            name='goal',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1, 'goal should be greater than zero')]),
        ),
        migrations.AlterField(
            model_name='projectsupport',
            name='price',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1, 'price must be greater than 0')]),
        ),
    ]
