# Generated by Django 3.2.5 on 2021-11-19 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_project_donate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='donate',
            new_name='count_donate',
        ),
        migrations.AddField(
            model_name='project',
            name='total_donate',
            field=models.IntegerField(default=0),
        ),
    ]
