# Generated by Django 3.2.5 on 2021-11-20 13:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0015_alter_projectsupport_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pleadge',
            name='price',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1, '目標金額必須大於 0')]),
        ),
        migrations.AlterField(
            model_name='pleadge',
            name='quantity',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1, '數量必須大於 0')]),
        ),
        migrations.AlterField(
            model_name='pleadge',
            name='supportprice',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1, '目標金額必須大於 0')]),
        ),
        migrations.AlterField(
            model_name='project',
            name='goal',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1, '目標金額必須大於 0 ')]),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, default='default_medium.jpg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='projectsupport',
            name='price',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1, '贊助價格必須大於 0')]),
        ),
    ]
