# Generated by Django 3.2.5 on 2021-11-20 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0016_auto_20211120_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('draft', '尚未設定贊助方案'), ('published', '募資上架')], default='draft', max_length=10),
        ),
    ]
