# Generated by Django 3.2.5 on 2021-11-27 02:01

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0017_project_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectName', models.CharField(max_length=50)),
                ('price', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1, '目標金額必須大於 0')])),
                ('issuedate', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('unpaid', '未付款'), ('paid', '付款'), ('expired', '失效')], default='unpaid', max_length=50)),
                ('supportname', models.CharField(max_length=50)),
                ('supportprice', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1, '目標金額必須大於 0')])),
                ('quantity', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1, '數量必須大於 0')])),
                ('projectsupport', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pledge', to='project.projectsupport')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'pledge',
                'verbose_name_plural': 'pledges',
            },
        ),
        migrations.DeleteModel(
            name='Pleadge',
        ),
    ]
