# Generated by Django 3.2.5 on 2021-11-27 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0018_auto_20211127_0201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pledge',
            name='status',
            field=models.CharField(choices=[('uncommit', '未成立'), ('unpaid', '未付款'), ('paid', '付款'), ('expired', '失效')], default='unpaid', max_length=50),
        ),
    ]
