# Generated by Django 3.2.5 on 2021-11-27 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0021_pledge_merchang_order_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pledge',
            old_name='merchang_order_id',
            new_name='merchant_order_no',
        ),
    ]
