# Generated by Django 3.2.5 on 2021-12-15 05:58

from django.db import migrations, models
import project.models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0022_rename_merchang_order_id_pledge_merchant_order_no'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('pk',), 'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, default='images/default_medium.jpg', upload_to=project.models.generate_image_position),
        ),
    ]
